# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetEmailSecurityBlockSendersResult',
    'AwaitableGetEmailSecurityBlockSendersResult',
    'get_email_security_block_senders',
    'get_email_security_block_senders_output',
]

@pulumi.output_type
class GetEmailSecurityBlockSendersResult:
    """
    A collection of values returned by getEmailSecurityBlockSenders.
    """
    def __init__(__self__, account_id=None, direction=None, id=None, max_items=None, order=None, pattern_type=None, results=None, search=None):
        if account_id and not isinstance(account_id, str):
            raise TypeError("Expected argument 'account_id' to be a str")
        pulumi.set(__self__, "account_id", account_id)
        if direction and not isinstance(direction, str):
            raise TypeError("Expected argument 'direction' to be a str")
        pulumi.set(__self__, "direction", direction)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if max_items and not isinstance(max_items, float):
            raise TypeError("Expected argument 'max_items' to be a float")
        pulumi.set(__self__, "max_items", max_items)
        if order and not isinstance(order, str):
            raise TypeError("Expected argument 'order' to be a str")
        pulumi.set(__self__, "order", order)
        if pattern_type and not isinstance(pattern_type, str):
            raise TypeError("Expected argument 'pattern_type' to be a str")
        pulumi.set(__self__, "pattern_type", pattern_type)
        if results and not isinstance(results, list):
            raise TypeError("Expected argument 'results' to be a list")
        pulumi.set(__self__, "results", results)
        if search and not isinstance(search, str):
            raise TypeError("Expected argument 'search' to be a str")
        pulumi.set(__self__, "search", search)

    @property
    @pulumi.getter(name="accountId")
    def account_id(self) -> str:
        return pulumi.get(self, "account_id")

    @property
    @pulumi.getter
    def direction(self) -> Optional[str]:
        return pulumi.get(self, "direction")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="maxItems")
    def max_items(self) -> Optional[float]:
        return pulumi.get(self, "max_items")

    @property
    @pulumi.getter
    def order(self) -> Optional[str]:
        return pulumi.get(self, "order")

    @property
    @pulumi.getter(name="patternType")
    def pattern_type(self) -> Optional[str]:
        return pulumi.get(self, "pattern_type")

    @property
    @pulumi.getter
    def results(self) -> Sequence['outputs.GetEmailSecurityBlockSendersResultResult']:
        return pulumi.get(self, "results")

    @property
    @pulumi.getter
    def search(self) -> Optional[str]:
        return pulumi.get(self, "search")


class AwaitableGetEmailSecurityBlockSendersResult(GetEmailSecurityBlockSendersResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetEmailSecurityBlockSendersResult(
            account_id=self.account_id,
            direction=self.direction,
            id=self.id,
            max_items=self.max_items,
            order=self.order,
            pattern_type=self.pattern_type,
            results=self.results,
            search=self.search)


def get_email_security_block_senders(account_id: Optional[str] = None,
                                     direction: Optional[str] = None,
                                     max_items: Optional[float] = None,
                                     order: Optional[str] = None,
                                     pattern_type: Optional[str] = None,
                                     search: Optional[str] = None,
                                     opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetEmailSecurityBlockSendersResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['direction'] = direction
    __args__['maxItems'] = max_items
    __args__['order'] = order
    __args__['patternType'] = pattern_type
    __args__['search'] = search
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('cloudflare:index/getEmailSecurityBlockSenders:getEmailSecurityBlockSenders', __args__, opts=opts, typ=GetEmailSecurityBlockSendersResult, package_ref=_utilities.get_package()).value

    return AwaitableGetEmailSecurityBlockSendersResult(
        account_id=pulumi.get(__ret__, 'account_id'),
        direction=pulumi.get(__ret__, 'direction'),
        id=pulumi.get(__ret__, 'id'),
        max_items=pulumi.get(__ret__, 'max_items'),
        order=pulumi.get(__ret__, 'order'),
        pattern_type=pulumi.get(__ret__, 'pattern_type'),
        results=pulumi.get(__ret__, 'results'),
        search=pulumi.get(__ret__, 'search'))
def get_email_security_block_senders_output(account_id: Optional[pulumi.Input[str]] = None,
                                            direction: Optional[pulumi.Input[Optional[str]]] = None,
                                            max_items: Optional[pulumi.Input[Optional[float]]] = None,
                                            order: Optional[pulumi.Input[Optional[str]]] = None,
                                            pattern_type: Optional[pulumi.Input[Optional[str]]] = None,
                                            search: Optional[pulumi.Input[Optional[str]]] = None,
                                            opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetEmailSecurityBlockSendersResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['direction'] = direction
    __args__['maxItems'] = max_items
    __args__['order'] = order
    __args__['patternType'] = pattern_type
    __args__['search'] = search
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('cloudflare:index/getEmailSecurityBlockSenders:getEmailSecurityBlockSenders', __args__, opts=opts, typ=GetEmailSecurityBlockSendersResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetEmailSecurityBlockSendersResult(
        account_id=pulumi.get(__response__, 'account_id'),
        direction=pulumi.get(__response__, 'direction'),
        id=pulumi.get(__response__, 'id'),
        max_items=pulumi.get(__response__, 'max_items'),
        order=pulumi.get(__response__, 'order'),
        pattern_type=pulumi.get(__response__, 'pattern_type'),
        results=pulumi.get(__response__, 'results'),
        search=pulumi.get(__response__, 'search')))
