# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetCustomHostnamesResult',
    'AwaitableGetCustomHostnamesResult',
    'get_custom_hostnames',
    'get_custom_hostnames_output',
]

@pulumi.output_type
class GetCustomHostnamesResult:
    """
    A collection of values returned by getCustomHostnames.
    """
    def __init__(__self__, direction=None, hostname=None, id=None, max_items=None, order=None, results=None, ssl=None, zone_id=None):
        if direction and not isinstance(direction, str):
            raise TypeError("Expected argument 'direction' to be a str")
        pulumi.set(__self__, "direction", direction)
        if hostname and not isinstance(hostname, str):
            raise TypeError("Expected argument 'hostname' to be a str")
        pulumi.set(__self__, "hostname", hostname)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if max_items and not isinstance(max_items, float):
            raise TypeError("Expected argument 'max_items' to be a float")
        pulumi.set(__self__, "max_items", max_items)
        if order and not isinstance(order, str):
            raise TypeError("Expected argument 'order' to be a str")
        pulumi.set(__self__, "order", order)
        if results and not isinstance(results, list):
            raise TypeError("Expected argument 'results' to be a list")
        pulumi.set(__self__, "results", results)
        if ssl and not isinstance(ssl, float):
            raise TypeError("Expected argument 'ssl' to be a float")
        pulumi.set(__self__, "ssl", ssl)
        if zone_id and not isinstance(zone_id, str):
            raise TypeError("Expected argument 'zone_id' to be a str")
        pulumi.set(__self__, "zone_id", zone_id)

    @property
    @pulumi.getter
    def direction(self) -> Optional[str]:
        return pulumi.get(self, "direction")

    @property
    @pulumi.getter
    def hostname(self) -> Optional[str]:
        return pulumi.get(self, "hostname")

    @property
    @pulumi.getter
    def id(self) -> Optional[str]:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="maxItems")
    def max_items(self) -> Optional[float]:
        return pulumi.get(self, "max_items")

    @property
    @pulumi.getter
    def order(self) -> str:
        return pulumi.get(self, "order")

    @property
    @pulumi.getter
    def results(self) -> Sequence['outputs.GetCustomHostnamesResultResult']:
        return pulumi.get(self, "results")

    @property
    @pulumi.getter
    def ssl(self) -> Optional[float]:
        return pulumi.get(self, "ssl")

    @property
    @pulumi.getter(name="zoneId")
    def zone_id(self) -> str:
        return pulumi.get(self, "zone_id")


class AwaitableGetCustomHostnamesResult(GetCustomHostnamesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetCustomHostnamesResult(
            direction=self.direction,
            hostname=self.hostname,
            id=self.id,
            max_items=self.max_items,
            order=self.order,
            results=self.results,
            ssl=self.ssl,
            zone_id=self.zone_id)


def get_custom_hostnames(direction: Optional[str] = None,
                         hostname: Optional[str] = None,
                         id: Optional[str] = None,
                         max_items: Optional[float] = None,
                         order: Optional[str] = None,
                         ssl: Optional[float] = None,
                         zone_id: Optional[str] = None,
                         opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetCustomHostnamesResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['direction'] = direction
    __args__['hostname'] = hostname
    __args__['id'] = id
    __args__['maxItems'] = max_items
    __args__['order'] = order
    __args__['ssl'] = ssl
    __args__['zoneId'] = zone_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('cloudflare:index/getCustomHostnames:getCustomHostnames', __args__, opts=opts, typ=GetCustomHostnamesResult, package_ref=_utilities.get_package()).value

    return AwaitableGetCustomHostnamesResult(
        direction=pulumi.get(__ret__, 'direction'),
        hostname=pulumi.get(__ret__, 'hostname'),
        id=pulumi.get(__ret__, 'id'),
        max_items=pulumi.get(__ret__, 'max_items'),
        order=pulumi.get(__ret__, 'order'),
        results=pulumi.get(__ret__, 'results'),
        ssl=pulumi.get(__ret__, 'ssl'),
        zone_id=pulumi.get(__ret__, 'zone_id'))
def get_custom_hostnames_output(direction: Optional[pulumi.Input[Optional[str]]] = None,
                                hostname: Optional[pulumi.Input[Optional[str]]] = None,
                                id: Optional[pulumi.Input[Optional[str]]] = None,
                                max_items: Optional[pulumi.Input[Optional[float]]] = None,
                                order: Optional[pulumi.Input[Optional[str]]] = None,
                                ssl: Optional[pulumi.Input[Optional[float]]] = None,
                                zone_id: Optional[pulumi.Input[str]] = None,
                                opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetCustomHostnamesResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['direction'] = direction
    __args__['hostname'] = hostname
    __args__['id'] = id
    __args__['maxItems'] = max_items
    __args__['order'] = order
    __args__['ssl'] = ssl
    __args__['zoneId'] = zone_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('cloudflare:index/getCustomHostnames:getCustomHostnames', __args__, opts=opts, typ=GetCustomHostnamesResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetCustomHostnamesResult(
        direction=pulumi.get(__response__, 'direction'),
        hostname=pulumi.get(__response__, 'hostname'),
        id=pulumi.get(__response__, 'id'),
        max_items=pulumi.get(__response__, 'max_items'),
        order=pulumi.get(__response__, 'order'),
        results=pulumi.get(__response__, 'results'),
        ssl=pulumi.get(__response__, 'ssl'),
        zone_id=pulumi.get(__response__, 'zone_id')))
