# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetZeroTrustTunnelCloudflaredsResult',
    'AwaitableGetZeroTrustTunnelCloudflaredsResult',
    'get_zero_trust_tunnel_cloudflareds',
    'get_zero_trust_tunnel_cloudflareds_output',
]

@pulumi.output_type
class GetZeroTrustTunnelCloudflaredsResult:
    """
    A collection of values returned by getZeroTrustTunnelCloudflareds.
    """
    def __init__(__self__, account_id=None, exclude_prefix=None, existed_at=None, id=None, include_prefix=None, is_deleted=None, max_items=None, name=None, results=None, status=None, uuid=None, was_active_at=None, was_inactive_at=None):
        if account_id and not isinstance(account_id, str):
            raise TypeError("Expected argument 'account_id' to be a str")
        pulumi.set(__self__, "account_id", account_id)
        if exclude_prefix and not isinstance(exclude_prefix, str):
            raise TypeError("Expected argument 'exclude_prefix' to be a str")
        pulumi.set(__self__, "exclude_prefix", exclude_prefix)
        if existed_at and not isinstance(existed_at, str):
            raise TypeError("Expected argument 'existed_at' to be a str")
        pulumi.set(__self__, "existed_at", existed_at)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if include_prefix and not isinstance(include_prefix, str):
            raise TypeError("Expected argument 'include_prefix' to be a str")
        pulumi.set(__self__, "include_prefix", include_prefix)
        if is_deleted and not isinstance(is_deleted, bool):
            raise TypeError("Expected argument 'is_deleted' to be a bool")
        pulumi.set(__self__, "is_deleted", is_deleted)
        if max_items and not isinstance(max_items, float):
            raise TypeError("Expected argument 'max_items' to be a float")
        pulumi.set(__self__, "max_items", max_items)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if results and not isinstance(results, list):
            raise TypeError("Expected argument 'results' to be a list")
        pulumi.set(__self__, "results", results)
        if status and not isinstance(status, str):
            raise TypeError("Expected argument 'status' to be a str")
        pulumi.set(__self__, "status", status)
        if uuid and not isinstance(uuid, str):
            raise TypeError("Expected argument 'uuid' to be a str")
        pulumi.set(__self__, "uuid", uuid)
        if was_active_at and not isinstance(was_active_at, str):
            raise TypeError("Expected argument 'was_active_at' to be a str")
        pulumi.set(__self__, "was_active_at", was_active_at)
        if was_inactive_at and not isinstance(was_inactive_at, str):
            raise TypeError("Expected argument 'was_inactive_at' to be a str")
        pulumi.set(__self__, "was_inactive_at", was_inactive_at)

    @property
    @pulumi.getter(name="accountId")
    def account_id(self) -> str:
        return pulumi.get(self, "account_id")

    @property
    @pulumi.getter(name="excludePrefix")
    def exclude_prefix(self) -> Optional[str]:
        return pulumi.get(self, "exclude_prefix")

    @property
    @pulumi.getter(name="existedAt")
    def existed_at(self) -> Optional[str]:
        return pulumi.get(self, "existed_at")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="includePrefix")
    def include_prefix(self) -> Optional[str]:
        return pulumi.get(self, "include_prefix")

    @property
    @pulumi.getter(name="isDeleted")
    def is_deleted(self) -> Optional[bool]:
        return pulumi.get(self, "is_deleted")

    @property
    @pulumi.getter(name="maxItems")
    def max_items(self) -> Optional[float]:
        return pulumi.get(self, "max_items")

    @property
    @pulumi.getter
    def name(self) -> Optional[str]:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def results(self) -> Sequence['outputs.GetZeroTrustTunnelCloudflaredsResultResult']:
        return pulumi.get(self, "results")

    @property
    @pulumi.getter
    def status(self) -> Optional[str]:
        return pulumi.get(self, "status")

    @property
    @pulumi.getter
    def uuid(self) -> Optional[str]:
        return pulumi.get(self, "uuid")

    @property
    @pulumi.getter(name="wasActiveAt")
    def was_active_at(self) -> Optional[str]:
        return pulumi.get(self, "was_active_at")

    @property
    @pulumi.getter(name="wasInactiveAt")
    def was_inactive_at(self) -> Optional[str]:
        return pulumi.get(self, "was_inactive_at")


class AwaitableGetZeroTrustTunnelCloudflaredsResult(GetZeroTrustTunnelCloudflaredsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetZeroTrustTunnelCloudflaredsResult(
            account_id=self.account_id,
            exclude_prefix=self.exclude_prefix,
            existed_at=self.existed_at,
            id=self.id,
            include_prefix=self.include_prefix,
            is_deleted=self.is_deleted,
            max_items=self.max_items,
            name=self.name,
            results=self.results,
            status=self.status,
            uuid=self.uuid,
            was_active_at=self.was_active_at,
            was_inactive_at=self.was_inactive_at)


def get_zero_trust_tunnel_cloudflareds(account_id: Optional[str] = None,
                                       exclude_prefix: Optional[str] = None,
                                       existed_at: Optional[str] = None,
                                       include_prefix: Optional[str] = None,
                                       is_deleted: Optional[bool] = None,
                                       max_items: Optional[float] = None,
                                       name: Optional[str] = None,
                                       status: Optional[str] = None,
                                       uuid: Optional[str] = None,
                                       was_active_at: Optional[str] = None,
                                       was_inactive_at: Optional[str] = None,
                                       opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetZeroTrustTunnelCloudflaredsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['excludePrefix'] = exclude_prefix
    __args__['existedAt'] = existed_at
    __args__['includePrefix'] = include_prefix
    __args__['isDeleted'] = is_deleted
    __args__['maxItems'] = max_items
    __args__['name'] = name
    __args__['status'] = status
    __args__['uuid'] = uuid
    __args__['wasActiveAt'] = was_active_at
    __args__['wasInactiveAt'] = was_inactive_at
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('cloudflare:index/getZeroTrustTunnelCloudflareds:getZeroTrustTunnelCloudflareds', __args__, opts=opts, typ=GetZeroTrustTunnelCloudflaredsResult, package_ref=_utilities.get_package()).value

    return AwaitableGetZeroTrustTunnelCloudflaredsResult(
        account_id=pulumi.get(__ret__, 'account_id'),
        exclude_prefix=pulumi.get(__ret__, 'exclude_prefix'),
        existed_at=pulumi.get(__ret__, 'existed_at'),
        id=pulumi.get(__ret__, 'id'),
        include_prefix=pulumi.get(__ret__, 'include_prefix'),
        is_deleted=pulumi.get(__ret__, 'is_deleted'),
        max_items=pulumi.get(__ret__, 'max_items'),
        name=pulumi.get(__ret__, 'name'),
        results=pulumi.get(__ret__, 'results'),
        status=pulumi.get(__ret__, 'status'),
        uuid=pulumi.get(__ret__, 'uuid'),
        was_active_at=pulumi.get(__ret__, 'was_active_at'),
        was_inactive_at=pulumi.get(__ret__, 'was_inactive_at'))
def get_zero_trust_tunnel_cloudflareds_output(account_id: Optional[pulumi.Input[str]] = None,
                                              exclude_prefix: Optional[pulumi.Input[Optional[str]]] = None,
                                              existed_at: Optional[pulumi.Input[Optional[str]]] = None,
                                              include_prefix: Optional[pulumi.Input[Optional[str]]] = None,
                                              is_deleted: Optional[pulumi.Input[Optional[bool]]] = None,
                                              max_items: Optional[pulumi.Input[Optional[float]]] = None,
                                              name: Optional[pulumi.Input[Optional[str]]] = None,
                                              status: Optional[pulumi.Input[Optional[str]]] = None,
                                              uuid: Optional[pulumi.Input[Optional[str]]] = None,
                                              was_active_at: Optional[pulumi.Input[Optional[str]]] = None,
                                              was_inactive_at: Optional[pulumi.Input[Optional[str]]] = None,
                                              opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetZeroTrustTunnelCloudflaredsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['excludePrefix'] = exclude_prefix
    __args__['existedAt'] = existed_at
    __args__['includePrefix'] = include_prefix
    __args__['isDeleted'] = is_deleted
    __args__['maxItems'] = max_items
    __args__['name'] = name
    __args__['status'] = status
    __args__['uuid'] = uuid
    __args__['wasActiveAt'] = was_active_at
    __args__['wasInactiveAt'] = was_inactive_at
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('cloudflare:index/getZeroTrustTunnelCloudflareds:getZeroTrustTunnelCloudflareds', __args__, opts=opts, typ=GetZeroTrustTunnelCloudflaredsResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetZeroTrustTunnelCloudflaredsResult(
        account_id=pulumi.get(__response__, 'account_id'),
        exclude_prefix=pulumi.get(__response__, 'exclude_prefix'),
        existed_at=pulumi.get(__response__, 'existed_at'),
        id=pulumi.get(__response__, 'id'),
        include_prefix=pulumi.get(__response__, 'include_prefix'),
        is_deleted=pulumi.get(__response__, 'is_deleted'),
        max_items=pulumi.get(__response__, 'max_items'),
        name=pulumi.get(__response__, 'name'),
        results=pulumi.get(__response__, 'results'),
        status=pulumi.get(__response__, 'status'),
        uuid=pulumi.get(__response__, 'uuid'),
        was_active_at=pulumi.get(__response__, 'was_active_at'),
        was_inactive_at=pulumi.get(__response__, 'was_inactive_at')))
