# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetCertificatePackResult',
    'AwaitableGetCertificatePackResult',
    'get_certificate_pack',
    'get_certificate_pack_output',
]

@pulumi.output_type
class GetCertificatePackResult:
    """
    A collection of values returned by getCertificatePack.
    """
    def __init__(__self__, certificate_pack_id=None, id=None, zone_id=None):
        if certificate_pack_id and not isinstance(certificate_pack_id, str):
            raise TypeError("Expected argument 'certificate_pack_id' to be a str")
        pulumi.set(__self__, "certificate_pack_id", certificate_pack_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if zone_id and not isinstance(zone_id, str):
            raise TypeError("Expected argument 'zone_id' to be a str")
        pulumi.set(__self__, "zone_id", zone_id)

    @property
    @pulumi.getter(name="certificatePackId")
    def certificate_pack_id(self) -> str:
        return pulumi.get(self, "certificate_pack_id")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="zoneId")
    def zone_id(self) -> str:
        return pulumi.get(self, "zone_id")


class AwaitableGetCertificatePackResult(GetCertificatePackResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetCertificatePackResult(
            certificate_pack_id=self.certificate_pack_id,
            id=self.id,
            zone_id=self.zone_id)


def get_certificate_pack(certificate_pack_id: Optional[str] = None,
                         zone_id: Optional[str] = None,
                         opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetCertificatePackResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['certificatePackId'] = certificate_pack_id
    __args__['zoneId'] = zone_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('cloudflare:index/getCertificatePack:getCertificatePack', __args__, opts=opts, typ=GetCertificatePackResult, package_ref=_utilities.get_package()).value

    return AwaitableGetCertificatePackResult(
        certificate_pack_id=pulumi.get(__ret__, 'certificate_pack_id'),
        id=pulumi.get(__ret__, 'id'),
        zone_id=pulumi.get(__ret__, 'zone_id'))
def get_certificate_pack_output(certificate_pack_id: Optional[pulumi.Input[str]] = None,
                                zone_id: Optional[pulumi.Input[str]] = None,
                                opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetCertificatePackResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['certificatePackId'] = certificate_pack_id
    __args__['zoneId'] = zone_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('cloudflare:index/getCertificatePack:getCertificatePack', __args__, opts=opts, typ=GetCertificatePackResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetCertificatePackResult(
        certificate_pack_id=pulumi.get(__response__, 'certificate_pack_id'),
        id=pulumi.get(__response__, 'id'),
        zone_id=pulumi.get(__response__, 'zone_id')))
